-- PAGES: config_api
UPDATE `sys_objects_page` SET `config_api`='{\r\n    layout: \'post\',\r\n    top: true,\r\n    blocks: {\r\n        author: {\r\n            name: \'bx_timeline:get_block_item_info\',\r\n            showTitle: false,\r\n            showBg: false,\r\n            forList: true,\r\n            forHeader: true,\r\n        },\r\n        text: {\r\n            name: \'bx_timeline:get_block_item\',\r\n            showTitle: false,\r\n            showBg: false,\r\n            forList: true,\r\n        },\r\n        \'comments-empty\': {\r\n            name: \'static:comments_empty\',\r\n            showTitle: false,\r\n            showBg: false,\r\n            forList: true,\r\n        },\r\n        comments: {\r\n            name: \'bx_timeline:get_block_item_comments\',\r\n            showTitle: false,\r\n            showBg: false,\r\n        },\r\n    },\r\n    headerSettings: {\r\n        header: false, \r\n        footer: false, \r\n        offset: false\r\n    },\r\n}' WHERE `object`='bx_timeline_item';

-- PAGES: active_api
UPDATE `sys_pages_blocks` SET `active_api`=1 WHERE `object`='bx_timeline_view' AND `module`='bx_timeline' AND `title_system`='_bx_timeline_page_block_title_system_post_profile' AND `title`='_bx_timeline_page_block_title_post_profile';
UPDATE `sys_pages_blocks` SET `active_api`=1 WHERE `object`='bx_timeline_view_home' AND `module`='bx_timeline' AND `title_system`='_bx_timeline_page_block_title_system_post_home' AND `title`='_bx_timeline_page_block_title_post_home';
UPDATE `sys_pages_blocks` SET `active_api`=1 WHERE `object`='bx_timeline_view_home' AND `module`='bx_timeline' AND `title_system`='_bx_timeline_page_block_title_system_view_home_outline' AND `title`='_bx_timeline_page_block_title_view_home_outline';
UPDATE `sys_pages_blocks` SET `active_api`=1 WHERE `object`='bx_timeline_view_hot' AND `module`='bx_timeline' AND `title_system`='_bx_timeline_page_block_title_system_view_hot_outline' AND `title`='_bx_timeline_page_block_title_view_hot_outline';
UPDATE `sys_pages_blocks` SET `active_api`=1 WHERE `object`='bx_timeline_item' AND `module`='bx_timeline' AND `title_system`='' AND `title`='_bx_timeline_page_block_title_item';
UPDATE `sys_pages_blocks` SET `active_api`=1 WHERE `object`='bx_timeline_item' AND `module`='bx_timeline' AND `title_system`='' AND `title`='_bx_timeline_page_block_title_item_comments';
UPDATE `sys_pages_blocks` SET `active_api`=1 WHERE `object`='bx_timeline_item' AND `module`='bx_timeline' AND `title_system`='' AND `title`='_bx_timeline_page_block_title_item_info';
UPDATE `sys_pages_blocks` SET `active_api`=1 WHERE `object`='bx_timeline_item_brief' AND `module`='bx_timeline' AND `title_system`='' AND `title`='_bx_timeline_page_block_title_item_content';
UPDATE `sys_pages_blocks` SET `active_api`=1 WHERE `object`='bx_timeline_manage' AND `module`='bx_timeline' AND `title_system`='' AND `title`='_bx_timeline_page_block_title_manage_own';
UPDATE `sys_pages_blocks` SET `active_api`=1 WHERE `object`='bx_timeline_manage' AND `module`='bx_timeline' AND `title_system`='' AND `title`='_bx_timeline_page_block_title_muted';
UPDATE `sys_pages_blocks` SET `active_api`=1 WHERE `object`='bx_timeline_administration' AND `module`='bx_timeline' AND `title_system`='_bx_timeline_page_block_title_system_manage_administration' AND `title`='_bx_timeline_page_block_title_manage';
UPDATE `sys_pages_blocks` SET `active_api`=1 WHERE `object`='bx_persons_view_profile' AND `module`='bx_timeline' AND `title_system`='_bx_timeline_page_block_title_system_view_profile' AND `title`='_bx_timeline_page_block_title_view_profile';
UPDATE `sys_pages_blocks` SET `active_api`=1 WHERE `object`='sys_home' AND `module`='bx_timeline' AND `title_system`='_bx_timeline_page_block_title_system_post_home' AND `title`='_bx_timeline_page_block_title_post_home';
